/// Embedded error code database derived from CMTrace binary analysis.
/// Contains common Windows, SCCM, and Windows Update error codes.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCategory {
    Windows,
    WindowsUpdate,
    Bits,
    ConfigMgr,
    Intune,
    DeliveryOpt,
    AppInstall,
    Certificate,
    Network,
    Security,
    Registry,
    FileSystem,
}

impl ErrorCategory {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Windows => "Windows",
            Self::WindowsUpdate => "Windows Update",
            Self::Bits => "BITS",
            Self::ConfigMgr => "ConfigMgr",
            Self::Intune => "Intune",
            Self::DeliveryOpt => "Delivery Optimization",
            Self::AppInstall => "App Install",
            Self::Certificate => "Certificate",
            Self::Network => "Network",
            Self::Security => "Security",
            Self::Registry => "Registry",
            Self::FileSystem => "File System",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ErrorCode {
    pub code: u32,
    pub description: &'static str,
    pub category: ErrorCategory,
}

pub static ERROR_CODES: &[ErrorCode] = &[
    // Common Windows/HRESULT errors
    ErrorCode { code: 0x00000000, description: "S_OK - The operation completed successfully", category: ErrorCategory::Windows },
    ErrorCode { code: 0x00000001, description: "S_FALSE - The operation completed with a non-critical warning", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004001, description: "E_NOTIMPL - Not implemented", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004002, description: "E_NOINTERFACE - No such interface supported", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004003, description: "E_POINTER - Invalid pointer", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004004, description: "E_ABORT - Operation aborted", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004005, description: "E_FAIL - Unspecified failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004006, description: "CO_E_INIT_TLS - Thread local storage failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80004015, description: "CO_E_WRONGOSFORAPP - Application not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8000FFFF, description: "E_UNEXPECTED - Unexpected failure", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80010105, description: "RPC_E_SERVERFAULT - The server threw an exception", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80010108, description: "RPC_E_DISCONNECTED - The object invoked has disconnected from its clients", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80040154, description: "REGDB_E_CLASSNOTREG - Class not registered", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80040201, description: "CACHE_E_NOCACHE_UPDATED - No cache updated", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070001, description: "ERROR_INVALID_FUNCTION - Incorrect function", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070002, description: "ERROR_FILE_NOT_FOUND - The system cannot find the file specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070003, description: "ERROR_PATH_NOT_FOUND - The system cannot find the path specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070005, description: "E_ACCESSDENIED - Access is denied", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070006, description: "ERROR_INVALID_HANDLE - The handle is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070008, description: "ERROR_NOT_ENOUGH_MEMORY - Not enough storage is available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000E, description: "E_OUTOFMEMORY - Not enough memory resources to complete this operation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007000F, description: "ERROR_INVALID_DRIVE - The system cannot find the drive specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070015, description: "ERROR_NOT_READY - The device is not ready", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070020, description: "ERROR_SHARING_VIOLATION - The process cannot access the file because it is being used by another process", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070032, description: "ERROR_NOT_SUPPORTED - The request is not supported", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070035, description: "ERROR_BAD_NETPATH - The network path was not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070043, description: "ERROR_BAD_NET_NAME - The network name cannot be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070052, description: "ERROR_DUP_NAME - Duplicate name on the network", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070057, description: "E_INVALIDARG - One or more arguments are invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007006E, description: "ERROR_OPEN_FAILED - The system cannot open the device or file specified", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070070, description: "ERROR_DISK_FULL - There is not enough space on the disk", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070079, description: "ERROR_SEM_TIMEOUT - The semaphore timeout period has expired", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007A, description: "ERROR_INSUFFICIENT_BUFFER - The data area passed to a system call is too small", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007B, description: "ERROR_INVALID_NAME - The filename, directory name, or volume label syntax is incorrect", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007E, description: "ERROR_MOD_NOT_FOUND - The specified module could not be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x8007007F, description: "ERROR_PROC_NOT_FOUND - The specified procedure could not be found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800700A1, description: "ERROR_BAD_PATHNAME - The specified path is invalid", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070102, description: "WAIT_TIMEOUT - The wait operation timed out", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070103, description: "NO_MORE_ITEMS - No more data is available", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704C7, description: "ERROR_CANCELLED - The operation was canceled by the user", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704CF, description: "ERROR_NETWORK_UNREACHABLE - The network location cannot be reached", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800704DD, description: "ERROR_NOT_LOGGED_ON - The user is not logged on", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070490, description: "E_ELEMENT_NOT_FOUND - Element not found", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070643, description: "ERROR_INSTALL_FAILURE - Fatal error during installation", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070652, description: "ERROR_INSTALL_ALREADY_RUNNING - Another installation is already in progress", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706BA, description: "RPC_S_SERVER_UNAVAILABLE - The RPC server is unavailable", category: ErrorCategory::Windows },
    ErrorCode { code: 0x800706BE, description: "RPC_S_CALL_FAILED - The remote procedure call failed", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070BC2, description: "ERROR_SUCCESS_REBOOT_REQUIRED - A restart is required to complete the install", category: ErrorCategory::Windows },
    ErrorCode { code: 0x80070BC9, description: "ERROR_FAIL_REBOOT_REQUIRED - A restart is required to complete the uninstall", category: ErrorCategory::Windows },

    // Windows Update Agent errors
    ErrorCode { code: 0x80240001, description: "WU_E_NO_SERVICE - Windows Update Agent was unable to provide the service", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240002, description: "WU_E_MAX_CAPACITY_REACHED - Maximum capacity of the service was exceeded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240003, description: "WU_E_UNKNOWN_ID - An ID that was not recognized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240004, description: "WU_E_NOT_INITIALIZED - The object could not be initialized", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240005, description: "WU_E_RANGEOVERLAP - The update handler requested a byte range overlapping a previously requested range", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240006, description: "WU_E_TOOMANYRANGES - Too many byte ranges requested", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240007, description: "WU_E_INVALIDINDEX - Invalid index into the update list", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240008, description: "WU_E_ITEMNOTFOUND - The key for the item queried could not be found", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240009, description: "WU_E_OPERATIONINPROGRESS - Another conflicting operation was in progress", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000A, description: "WU_E_COULDNOTCANCEL - Cancellation of the operation was not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000B, description: "WU_E_CALL_CANCELLED - Operation was cancelled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000C, description: "WU_E_NOOP - No operation was required", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000D, description: "WU_E_XML_MISSINGDATA - XML is missing required data", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000E, description: "WU_E_XML_INVALID - XML is not valid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024000F, description: "WU_E_CYCLE_DETECTED - Circular update relationships were detected", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240010, description: "WU_E_TOO_DEEP_RELATION - Update relationships too deep to evaluate", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240011, description: "WU_E_INVALID_RELATIONSHIP - Invalid update relationship", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240012, description: "WU_E_REG_VALUE_INVALID - Invalid registry value", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240013, description: "WU_E_DUPLICATE_ITEM - Duplicate item in list", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240016, description: "WU_E_INSTALL_NOT_ALLOWED - Install not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240017, description: "WU_E_NOT_APPLICABLE - The update is not applicable to this computer", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240018, description: "WU_E_NO_USERTOKEN - Failed to use the BITS service", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240019, description: "WU_E_EXCLUSIVE_INSTALL_CONFLICT - An exclusive update cannot be installed with other updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001A, description: "WU_E_POLICY_NOT_SET - A policy value was not set", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001B, description: "WU_E_SELFUPDATE_IN_PROGRESS - Self-update in progress", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001D, description: "WU_E_INVALID_UPDATE - An update contains invalid metadata", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001E, description: "WU_E_SERVICE_STOP - Service stop required", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024001F, description: "WU_E_NO_CONNECTION - No network connection was available", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240020, description: "WU_E_NO_INTERACTIVE_USER - Operation cannot continue without user interaction", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240021, description: "WU_E_TIME_OUT - Operation did not complete because it timed out", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240022, description: "WU_E_ALL_UPDATES_FAILED - Operation failed for all updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240024, description: "WU_E_NO_UPDATE - There are no updates", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240025, description: "WU_E_USER_ACCESS_DISABLED - Group policy has disabled user access", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240026, description: "WU_E_INVALID_UPDATE_TYPE - The type of update is invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240027, description: "WU_E_URL_TOO_LONG - The URL exceeded the maximum length", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240028, description: "WU_E_UNINSTALL_NOT_ALLOWED - The update could not be uninstalled", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240029, description: "WU_E_INVALID_PRODUCT_LICENSE - Search may have missed some updates due to expired product license", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002A, description: "WU_E_MISSING_HANDLER - A component required to detect updates was missing", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002B, description: "WU_E_LEGACYSERVER - An operation did not complete because it requires a newer version of server", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002C, description: "WU_E_BIN_SOURCE_ABSENT - A delta-compressed update could not be installed because it required the source", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002D, description: "WU_E_SOURCE_ABSENT - A full-file update could not be installed because it required the source", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002E, description: "WU_E_WU_DISABLED - Access to an unmanaged server is not allowed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x8024002F, description: "WU_E_CALL_CANCELLED_BY_POLICY - Operation did not complete because DisableWindowsUpdateAccess policy was set", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240030, description: "WU_E_INVALID_PROXY_SERVER - The format of the proxy list was invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240031, description: "WU_E_INVALID_FILE - The file is in the wrong format", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240032, description: "WU_E_INVALID_CRITERIA - The search criteria string was invalid", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240033, description: "WU_E_EULA_UNAVAILABLE - License terms could not be downloaded", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240035, description: "WU_E_UPDATE_NOT_PROCESSED - The update was not processed", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240036, description: "WU_E_INVALID_OPERATION - The objects current state does not allow the operation", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240037, description: "WU_E_NOT_SUPPORTED - The functionality is not supported", category: ErrorCategory::WindowsUpdate },
    ErrorCode { code: 0x80240FFF, description: "WU_E_UNEXPECTED - An operation failed due to reasons not covered by another error code", category: ErrorCategory::WindowsUpdate },

    // BITS errors
    ErrorCode { code: 0x80200001, description: "BG_E_NOT_FOUND - The requested job was not found", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200002, description: "BG_E_INVALID_STATE - The requested action is not allowed in the current job state", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200003, description: "BG_E_EMPTY - The job is empty", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200005, description: "BG_E_FILE_NOT_AVAILABLE - A file in the job is not available", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200010, description: "BG_E_NETWORK_DISCONNECTED - BITS is unable to contact the server", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200013, description: "BG_E_INSUFFICIENT_HTTP_SUPPORT - The server does not support the necessary HTTP protocol", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200014, description: "BG_E_INSUFFICIENT_RANGE_SUPPORT - The server does not support the necessary HTTP byte range", category: ErrorCategory::Bits },
    ErrorCode { code: 0x80200022, description: "BG_E_HTTP_ERROR_403 - The server requires HTTP authentication", category: ErrorCategory::Bits },

    // ConfigMgr/SCCM specific
    ErrorCode { code: 0x80040600, description: "CCM_E_CONTENT_NOT_FOUND - Content not found on distribution point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040601, description: "CCM_E_BAD_SITE_CODE - Invalid site code", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040602, description: "CCM_E_NOT_CONNECTED - Not connected to management point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040690, description: "CCM_E_NO_MANAGEMENT_POINT - Could not discover management point", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80040692, description: "CCM_E_TIMEOUT - CCM operation timed out", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041001, description: "WMI_E_FAILED - WMI generic failure", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041002, description: "WMI_E_NOT_FOUND - WMI object not found", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041003, description: "WMI_E_ACCESS_DENIED - WMI access denied", category: ErrorCategory::ConfigMgr },
    ErrorCode { code: 0x80041006, description: "WMI_E_OUT_OF_MEMORY - WMI out of memory", category: ErrorCategory::ConfigMgr },

    // Delivery Optimization
    ErrorCode { code: 0x80D01001, description: "DO_E_DOWNLOAD_NOT_FOUND - Download not found", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02002, description: "DO_E_DOWNLOAD_CANCELLED - Download was cancelled", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D02005, description: "DO_E_NO_DOWNLOAD_SOURCES - No download sources available", category: ErrorCategory::DeliveryOpt },
    ErrorCode { code: 0x80D06005, description: "DO_E_BLOCKED_BY_POLICY - Download blocked by policy", category: ErrorCategory::DeliveryOpt },

    // App installation / MSI
    ErrorCode { code: 0x80070641, description: "ERROR_INSTALL_SERVICE_FAILURE - The Windows Installer Service could not be accessed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070642, description: "ERROR_INSTALL_USEREXIT - User cancelled installation", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070644, description: "ERROR_INSTALL_SUSPEND - Installation suspended", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070645, description: "ERROR_UNKNOWN_PRODUCT - Unknown product", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x80070660, description: "ERROR_INSTALL_REMOTE_DISALLOWED - Remote installations are not allowed", category: ErrorCategory::AppInstall },

    // Certificate errors
    ErrorCode { code: 0x800B0100, description: "TRUST_E_NOSIGNATURE - No signature was present in the subject", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0101, description: "CERT_E_EXPIRED - A required certificate is not within its validity period", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B0109, description: "CERT_E_UNTRUSTEDROOT - A certificate chain processed but terminated in a root certificate not trusted", category: ErrorCategory::Certificate },
    ErrorCode { code: 0x800B010A, description: "CERT_E_CHAINING - A certificate chain could not be built to a trusted root authority", category: ErrorCategory::Certificate },

    // Intune/MDM specific
    ErrorCode { code: 0x87D00215, description: "INTUNEWIN_E_INSTALL_FAILURE - The application installation failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D00324, description: "INTUNEWIN_E_DETECTION_FAILED - Post-install detection failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D00607, description: "INTUNEWIN_E_DOWNLOAD_FAILED - Content download failed", category: ErrorCategory::Intune },
    ErrorCode { code: 0x87D01101, description: "INTUNEWIN_E_TIMEOUT - Application install timed out", category: ErrorCategory::Intune },

    // WinGet
    ErrorCode { code: 0x8A150001, description: "APPINSTALLER_CLI_ERROR_INTERNAL - Internal error", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150002, description: "APPINSTALLER_CLI_ERROR_INVALID_CL - Invalid command line", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150003, description: "APPINSTALLER_CLI_ERROR_COMMAND_FAILED - Command failed", category: ErrorCategory::AppInstall },
    ErrorCode { code: 0x8A150014, description: "APPINSTALLER_CLI_ERROR_NO_APPLICABLE_INSTALLER - No applicable installer found", category: ErrorCategory::AppInstall },
];
